export const DEVELOPERS = [
  { id:'d1', name:'Alice Chen',  initials:'AC',
    role: 'Full-stack engineer — auth & onboarding',
    desc: 'Owns the user identity service and drives the UX redesign initiative. Specialises in authentication flows and frontend component architecture.',
    criteria: ['Feature code & unit tests merged','Auth-related PRs peer-reviewed','Agent outputs reviewed and accepted','Staging deployment signed off','Ticket moved to Done in tracker'],
    outputs: ['Merged pull requests','Code review approvals','Deployment authorisation'] },
  { id:'d2', name:'Bob Kim',     initials:'BK',
    role: 'Backend engineer — pipelines & QA',
    desc: 'Primary owner of the batch processing system and E2E test infrastructure. Diagnoses data-pipeline issues and validates all QA agent output before merge.',
    criteria: ['Pipeline issues root-caused and fixed','E2E suites extended and green','QA agent output validated','Nightly batch job stable for 3 runs','Performance benchmarks met'],
    outputs: ['Pipeline fix PRs','Validated test suites','Nightly job health reports'] },
  { id:'d3', name:'Carol Davis', initials:'CD',
    role: 'DevOps & platform engineer',
    desc: 'Owns the CI/CD infrastructure, database operations, and platform reliability. Ensures zero-downtime deployments and reviews all DeployBot staging outputs.',
    criteria: ['CI/CD pipeline green end-to-end','Database migration executed safely','Staging environment healthy','Rollback procedure documented','SLO targets maintained'],
    outputs: ['Pipeline configuration','Migration scripts','Staging health reports'] },
];

export const AGENTS = [
  { id:'a1', name:'CodeBot',   type:'Code Review', developerId:'d1',
    desc: 'Analyses diffs for style violations, security anti-patterns, and test coverage drops before human review begins. Runs after every push to an open PR.',
    criteria: ['All inline comments resolved or dismissed','No critical security findings open','Coverage did not drop below threshold','Refactoring suggestions acknowledged','Final review approved by CodeBot'],
    outputs: ['Inline code review comments','Security vulnerability report','Coverage delta analysis','Refactoring suggestion list'] },
  { id:'a2', name:'QA-7',      type:'QA',          developerId:'d2',
    desc: 'Generates, runs, and reports on Playwright E2E test suites for checkout and pipeline flows. Blocks merge if any critical test path fails.',
    criteria: ['12+ test cases authored','Happy-path checkout fully covered','Promo-code edge cases tested','All tests passing in CI','Coverage report attached to PR'],
    outputs: ['Playwright test suite','CI test run report','Coverage HTML report','Edge case log'] },
  { id:'a3', name:'DeployBot', type:'DevOps',       developerId:'d3',
    desc: 'Orchestrates CI/CD runs, monitors GitHub Actions pipelines, manages staging deployments, and triggers automated rollback on health-check failure.',
    criteria: ['Build stage passes (< 3 min)','Test stage passes (100% green)','Staging deploy confirmed healthy','Deploy metrics within SLO','Rollback tested and documented'],
    outputs: ['Build pass/fail report','Staging deploy confirmation','Pipeline timing metrics','Rollback trigger log'] },
  { id:'a4', name:'DesignAI',  type:'Design',       developerId:'d1',
    desc: 'Generates high-fidelity Figma screen designs following the design system tokens. Annotates frames for developer handoff and exports responsive breakpoint specs.',
    criteria: ['3 onboarding screens completed in Figma','Mobile-responsive variants included','All design tokens applied correctly','Stakeholder review sign-off received','Dev handoff annotations complete'],
    outputs: ['Figma frame exports','Design token mapping','Responsive breakpoint specs','Dev handoff annotation layer'] },
];

export const SUB_AGENTS = [
  { id:'sa1', name:'LintBot',     type:'Syntax Linter',   parentId:'a1',
    desc: 'Runs ESLint and Prettier across all changed files. Flags style violations, unused variables, and formatting inconsistencies.',
    criteria: ['Zero ESLint errors in changed files','Prettier formatting applied','No unused imports remaining','Auto-fix patch reviewed and accepted'],
    outputs: ['Lint report','Auto-fix patch','Violation count by rule'] },
  { id:'sa2', name:'SecScan',     type:'Security Audit',  parentId:'a1',
    desc: 'Scans code for OWASP Top 10 vulnerabilities, exposed secrets, and dependency CVEs using Semgrep and npm audit.',
    criteria: ['No critical OWASP findings','No exposed secrets in diff','All high-severity CVEs patched or accepted','Security report signed off by lead'],
    outputs: ['OWASP findings report','CVE dependency list','Secret exposure alerts'] },
  { id:'sa3', name:'TestRunner',  type:'Playwright E2E',  parentId:'a2',
    desc: 'Executes the full Playwright E2E suite in headless Chromium against the staging environment. Captures screenshots on failure.',
    criteria: ['All test cases executed','Zero failing tests on happy path','Flaky tests retried and resolved','Screenshots archived for failures','Execution time < 8 minutes'],
    outputs: ['Test results (pass/fail per case)','Failure screenshot artefacts','Execution time report'] },
  { id:'sa4', name:'CoverageBot', type:'Coverage Report', parentId:'a2',
    desc: 'Measures code coverage after test runs and reports delta against the main branch threshold.',
    criteria: ['Coverage ≥ 80% on changed files','Delta report attached to PR','No new uncovered critical paths','Coverage gate passed in CI'],
    outputs: ['Coverage percentage','Uncovered file list','Coverage delta vs main'] },
  { id:'sa5', name:'StageBot',    type:'Staging Deploy',  parentId:'a3',
    desc: 'Pushes Docker images to the staging environment, runs health checks on every endpoint, and reports deployment status with rollback command.',
    criteria: ['Docker image pushed and tagged','All health checks green','Staging URL verified accessible','Deployment logged with timestamp','Rollback command confirmed working'],
    outputs: ['Deploy confirmation','Health check results','Staging URL','Rollback command'] },
];

export const TASKS = [
  { id:'t1', title:'Refactor auth module',       desc:'Break monolithic auth into testable repository units', status:'progress', developerId:'d1', agentId:'a1', assigneeType:'dev', agentAssigned:true,
    priority:'critical', dueDate:'2026-04-03',
    overview: 'The authentication module is a 2,400-line monolith that mixes concerns and makes isolated testing impossible. This task decomposes it into focused repositories following the repository pattern.',
    criteria:['Auth decomposed into ≤ 5 repository classes','JWT validation enforced server-side only','Rate limiter active on /login (max 5 req/min)','No hardcoded secrets in any config file','All 47 existing auth tests pass','Peer review approved by senior engineer'] },
  { id:'t2', title:'E2E tests — checkout',       desc:'Cover happy-path and promo edge cases with Playwright', status:'todo', developerId:'d2', agentId:'a2', assigneeType:'dev', agentAssigned:true,
    priority:'high', dueDate:'2026-04-08',
    overview: 'The checkout flow currently has zero E2E coverage. A recent release broke promo-code stacking silently. This task establishes a comprehensive Playwright suite to catch regressions early.',
    criteria:['12+ test cases covering checkout flow','Happy-path cart → payment → confirmation covered','Invalid, expired, and stacking promo codes tested','All tests passing in CI on every PR','Coverage report attached and reviewed','Flaky tests eliminated before merge'] },
  { id:'t3', title:'CI/CD pipeline setup',       desc:'GitHub Actions: build → test → staging deploy on merge', status:'done', developerId:'d3', agentId:'a3', assigneeType:'dev',
    priority:'medium', dueDate:'2026-03-28',
    overview: 'Establish an automated GitHub Actions pipeline so every PR merge triggers a full build, test, and staging deployment without manual intervention.',
    criteria:['YAML config merged to main branch','Build stage completes in < 3 min','Test stage runs all suites green','Staging deploy triggered automatically on merge','Average total pipeline time < 6 min','Rollback procedure documented in runbook'] },
  { id:'t4', title:'Onboarding screen redesign', desc:'High-fidelity Figma mockups for 3-step onboarding', status:'todo', developerId:'d1', agentId:'a4', assigneeType:'agent',
    priority:'high', dueDate:'2026-04-10',
    overview: 'User research shows a 62 % drop-off during onboarding. This task produces high-fidelity redesigned screens for the 3-step flow, incorporating UX research findings and new design system tokens.',
    criteria:['All 3 onboarding screens designed in Figma','Mobile-responsive variants at 375 px and 768 px','All design-system tokens applied (no raw hex values)','Progress-bar component included on all steps','Stakeholder review sign-off recorded','Dev handoff annotations on every frame'] },
  { id:'t5', title:'Fix batch job memory leak',  desc:'Profile nightly job — suspect unclosed stream handles', status:'blocked', developerId:'d2', agentId:'a2', assigneeType:'agent',
    priority:'critical', dueDate:'2026-04-04',
    overview: 'The nightly ETL batch job crashes with OOM around 03:00 UTC, corrupting partial outputs. Root cause is suspected to be unclosed ReadableStream handles in the CSV ingestion loop.',
    criteria:['Root cause identified and documented','Heap profiler report attached to ticket','Fix deployed and validated on staging','3 consecutive clean nightly runs observed','Memory usage stays below 512 MB throughout run','Post-mortem written and shared with team'] },
  { id:'t6', title:'PostgreSQL 16 migration',    desc:'Upgrade schema, pool config, and validate query perf', status:'progress', developerId:'d3', agentId:'a3',
    priority:'medium', dueDate:'2026-04-18',
    overview: 'Upgrade the production database from PostgreSQL 14 to 16 to gain access to logical replication improvements and security patches. Requires schema validation, pool reconfiguration, and a zero-downtime cutover plan.',
    criteria:['Migration script tested on staging clone','All queries validated against PG16 planner','Connection pool config updated for new defaults','Performance benchmarks match or exceed PG14 baseline','Zero-downtime cutover plan documented','Rollback to PG14 verified possible within 15 min'] },
];
